# Generated by Django 5.2.3 on 2025-07-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_App', '0002_curso_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('entregado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_primer_App.estudiante')),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
