# Generated by Django 5.2.3 on 2025-07-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_App', '0003_entregable_delete_familiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_inscripcion',
        ),
    ]
